import XCTest
import KeyboardShortcuts
@testable import MeowOut

final class ClipboardHistorySettingsTests: XCTestCase {
    private var suiteName: String!
    private var defaults: UserDefaults!

    override func setUp() {
        super.setUp()
        suiteName = "ClipboardHistorySettingsTests-\(UUID().uuidString)"
        defaults = UserDefaults(suiteName: suiteName)!
    }

    override func tearDown() {
        defaults.removePersistentDomain(forName: suiteName)
        defaults = nil
        suiteName = nil
        super.tearDown()
    }

    func testDefaultValuesMatchSpec() {
        let settings = ClipboardHistorySettings(defaults: defaults)

        XCTAssertTrue(settings.isEnabled)
        XCTAssertEqual(settings.historyLimit, 200)
        XCTAssertTrue(settings.recordText)
        XCTAssertTrue(settings.recordRichText)
        XCTAssertTrue(settings.recordImages)
        XCTAssertTrue(settings.recordFiles)
        XCTAssertFalse(settings.pasteAutomatically)
        XCTAssertFalse(settings.removeFormattingByDefault)
        XCTAssertEqual(settings.sortMode, .lastCopiedAt)
        XCTAssertEqual(settings.ignoredApplications, [])
        XCTAssertTrue(settings.ignoredPasteboardTypes.contains("org.nspasteboard.TransientType"))
        XCTAssertTrue(settings.ignoredPasteboardTypes.contains("org.nspasteboard.ConcealedType"))
        XCTAssertTrue(settings.ignoredPasteboardTypes.contains("org.nspasteboard.AutoGeneratedType"))
    }

    func testHistoryLimitClampsToSupportedRange() {
        let settings = ClipboardHistorySettings(defaults: defaults)

        settings.historyLimit = 0
        XCTAssertEqual(settings.historyLimit, 1)

        settings.historyLimit = 10_000
        XCTAssertEqual(settings.historyLimit, 999)
    }
}
