import Foundation

public final class ClipboardHistorySettings {
    public static let shared = ClipboardHistorySettings()

    public static let defaultIgnoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public enum SortMode: String, Codable, CaseIterable, Identifiable {
        case lastCopiedAt
        case createdAt
        case copyCount

        public var id: String { rawValue }
    }

    private enum Keys {
        static let isEnabled = "clipboardHistory.isEnabled"
        static let historyLimit = "clipboardHistory.historyLimit"
        static let recordText = "clipboardHistory.recordText"
        static let recordRichText = "clipboardHistory.recordRichText"
        static let recordImages = "clipboardHistory.recordImages"
        static let recordFiles = "clipboardHistory.recordFiles"
        static let pasteAutomatically = "clipboardHistory.pasteAutomatically"
        static let removeFormattingByDefault = "clipboardHistory.removeFormattingByDefault"
        static let sortMode = "clipboardHistory.sortMode"
        static let ignoredApplications = "clipboardHistory.ignoredApplications"
        static let ignoredPasteboardTypes = "clipboardHistory.ignoredPasteboardTypes"
    }

    private let defaults: UserDefaults

    public init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
    }

    public var isEnabled: Bool {
        get { bool(forKey: Keys.isEnabled, defaultValue: true) }
        set { defaults.set(newValue, forKey: Keys.isEnabled) }
    }

    public var historyLimit: Int {
        get {
            let value = defaults.object(forKey: Keys.historyLimit) as? Int ?? 200
            return clampHistoryLimit(value)
        }
        set {
            defaults.set(clampHistoryLimit(newValue), forKey: Keys.historyLimit)
        }
    }

    public var recordText: Bool {
        get { bool(forKey: Keys.recordText, defaultValue: true) }
        set { defaults.set(newValue, forKey: Keys.recordText) }
    }

    public var recordRichText: Bool {
        get { bool(forKey: Keys.recordRichText, defaultValue: true) }
        set { defaults.set(newValue, forKey: Keys.recordRichText) }
    }

    public var recordImages: Bool {
        get { bool(forKey: Keys.recordImages, defaultValue: true) }
        set { defaults.set(newValue, forKey: Keys.recordImages) }
    }

    public var recordFiles: Bool {
        get { bool(forKey: Keys.recordFiles, defaultValue: true) }
        set { defaults.set(newValue, forKey: Keys.recordFiles) }
    }

    public var pasteAutomatically: Bool {
        get { bool(forKey: Keys.pasteAutomatically, defaultValue: false) }
        set { defaults.set(newValue, forKey: Keys.pasteAutomatically) }
    }

    public var removeFormattingByDefault: Bool {
        get { bool(forKey: Keys.removeFormattingByDefault, defaultValue: false) }
        set { defaults.set(newValue, forKey: Keys.removeFormattingByDefault) }
    }

    public var sortMode: SortMode {
        get {
            let rawValue = defaults.string(forKey: Keys.sortMode) ?? SortMode.lastCopiedAt.rawValue
            return SortMode(rawValue: rawValue) ?? .lastCopiedAt
        }
        set {
            defaults.set(newValue.rawValue, forKey: Keys.sortMode)
        }
    }

    public var ignoredApplications: Set<String> {
        get { stringSet(forKey: Keys.ignoredApplications, defaultValue: []) }
        set { defaults.set(Array(newValue), forKey: Keys.ignoredApplications) }
    }

    public var ignoredPasteboardTypes: Set<String> {
        get {
            stringSet(
                forKey: Keys.ignoredPasteboardTypes,
                defaultValue: Self.defaultIgnoredPasteboardTypes
            )
        }
        set { defaults.set(Array(newValue), forKey: Keys.ignoredPasteboardTypes) }
    }

    public func restoreDefaultIgnoredPasteboardTypes() {
        ignoredPasteboardTypes = Self.defaultIgnoredPasteboardTypes
    }

    private func bool(forKey key: String, defaultValue: Bool) -> Bool {
        defaults.object(forKey: key) as? Bool ?? defaultValue
    }

    private func stringSet(forKey key: String, defaultValue: Set<String>) -> Set<String> {
        guard let values = defaults.stringArray(forKey: key) else {
            return defaultValue
        }

        return Set(values)
    }

    private func clampHistoryLimit(_ value: Int) -> Int {
        min(max(value, 1), 999)
    }
}
